 source 'http://rubygems.org'

 gem 'capybara'
 gem 'cucumber', '3.1.2'
 gem 'ffaker'
 gem 'parallel_tests'
 gem 'poltergeist'
 gem 'pry'
 gem 'rake'
 gem 'report_builder'
 gem 'rspec'
 gem 'selenium-webdriver'
 gem 'png_quantizator'
